services:
  - type: web
    name: stylesathi-backend
    env: python
    buildCommand: |
      pip install -r backend/requirements.txt
      python backend/manage.py collectstatic --noinput
      python backend/manage.py migrate
    startCommand: gunicorn stylesathi_backend.wsgi:application --chdir backend --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_ALLOWED_HOSTS
        value: stylesathi-backend.onrender.com,stylesathi-frontend.onrender.com
      - key: DJANGO_DEBUG
        value: false
  - type: static_site
    name: stylesathi-frontend
    buildCommand: |
      cd styleSathi
      npm ci
      npm run build
    publishPath: styleSathi/dist
    headers:
      - path: /assets/**
        name: Content-Type
        value: text/css
